### PR TITLE
forked anvil deployment

### PR DESCRIPTION
**Pull request by shafu0x**
this allows you to deploy the contracts locally on a forked gnosis chain

### CODE REVIEW

**Review by petrovska-petro — COMMENTED** [review]
this is v handy for local testing!

is there a way while calling `make deployAnvil` to force to be using one of 10 funded accounts on the anvil spin up by default? instead of requiring using a pk in the `.env` file w/ enough funds to avoid trigger erro msgs related not enough gas etc?

**Comment by shafu0x** [comment]
that is what `--gas-price 0` is for. you can use any account.

**Comment by petrovska-petro** [comment]
> that is what `--gas-price 0` is for. you can use any account.

oh nice. did not know

initially w/ a random pk in `.env`. got the following err msg (prob i messed up the pk value 😆):

```
Context:
- server returned an error response: error code -32003: Insufficient funds for gas * price + value
make: *** [deployAnvil] Error 1
```

now using one of the pk generated by anvil, all lg! ✅

**Review by petrovska-petro — DISMISSED** [review]

**Comment by gosuto-inzasheru** [comment]
fixed merge conflict

**Review by petrovska-petro — APPROVED** [review]

**Pull request merged**
