### PR TITLE
feat: use balancer queries

### PR DESCRIPTION
**Pull request by gosuto-inzasheru**
alternative way. not sure if it is worth all the gas

### CODE REVIEW

**Review by petrovska-petro — COMMENTED** [review]
generally these methods such as `queryExit`, `queryJoin` and alike from the queries contract it is not advisable to call it directly on-chain on the tx which will get exec immediately, but in this case since it has a delay between queuing and actually exec i can see that we could leverage it and being less prone to manipulations, which i think its the reason that in their docs advise against use it in such scenarios

another way to skin the cat could be to use those same methods in the checker (offchain) and pass it as an arg in the `adjustPool` method, so there is not "exposure" to the actual calc directly on-chain

**Comment by petrovska-petro** [comment]
what is the gas diff between the `balancequeries` approach vs #27 ?

**Comment by gosuto-inzasheru** [comment]
closing (for now!) in favour of the more simple approach in #27

**Comment by gosuto-inzasheru** [comment]
there is also `queryBatchSwap` and similar relayer queries

**Pull request closed without merging**
