### PR TITLE
fix: remove expired check in `checkUpkeep`

### LINKED ISSUE #88: feat: `checkUpkeep` will not clean expired txs if `adjustPool` cannot be called
Separate the clean-up actions as an independent action type in `PoolAction`. it may automatically help solving #87 to unlock the queue but way more slower solution as expire time is ~30min

### PR DESCRIPTION
**Pull request by gosuto-inzasheru**
closes #88 

since cleaning the queue is permissionless, there is no need to pass it through the timelock. it can simply be called by the vmodule while queueing up a tx

### CODE REVIEW

**Review by petrovska-petro — COMMENTED** [review]
good shuffle of condition checks for triggering clean up when another normal action will get queue

nice test addition  `test_When_QueueHasInternalExpiredTxs`. not sure if that ever will happen in prod tho, otherwise i think we have a bigger problem w/ the keeper system allowing an internal tx being expired 

imagine that actually it happens should not at some point actually happen also a storage clean-up, meaning `delete queuedTx;`? otherwise when calling `_executeQueuedTx` will be trying to exec an expired payload, no?

**Comment by gosuto-inzasheru** [comment]
> imagine that actually it happens should not at some point actually happen also a storage clean-up, meaning `delete queuedTx;`? otherwise when calling `_executeQueuedTx` will be trying to exec an expired payload, no?

i fixed this by only returning `EXEC_QUEUE_POOL_ACTION` if `!_isCleanQueueRequired()`. otherwise, it will look for an actual pool action. this in turn will call `_queueTx` with the new action, overwriting the exipred one. ie cleanup should only occur _as part of a (new) action_, not by itself

lmk if you agree :D

**Comment by gosuto-inzasheru** [comment]
hmm what do you think of this
```
Warning (8760): This declaration has the same name as another declaration.
   --> src/RoboSaverVirtualModule.sol:266:[13](https://github.com/onchainification/robosaver/actions/runs/9939898449/job/27456020086#step:7:14):
    |
266 |             uint256 deficit = dailyAllowance - balance + buffer;
    |             ^^^^^^^^^^^^^^^
Note: The other declaration is here:
   --> src/RoboSaverVirtualModule.sol:300:5:
    |
300 |     function deficit() external view returns (uint256 deficit_) {
    |     ^ (Relevant source part starts here and spans across multiple lines).
```

**Comment by petrovska-petro** [comment]
> re the warning of duplication for `surplus` and `deficit`

i like those methods `deficit()` & `surplus()`, but why not make them instead `public view`? 🤔 

as a simple solution is that those internal variables used in `checkUpkeep` could be added a prefix/suffix to avoid the duplication. e.g: `_deficit`, `deficitShadow`

**Comment by petrovska-petro** [comment]
> i fixed this by only returning EXEC_QUEUE_POOL_ACTION if !_isCleanQueueRequired(). otherwise, it will look for an actual pool action. this in turn will call _queueTx with the new action, overwriting the exipred one. ie cleanup should only occur as part of a (new) action, not by itself

i think is a valid solution

really nice test flow in `test_When_QueueHasInternalExpiredTxs` mirroring actual actions triggering each behaviour 🔥

**Review by petrovska-petro — APPROVED** [review]

**Pull request merged**
