### PR TITLE
ci: dry run deployment script

### LINKED ISSUE #95: ci: dry run deploy commands in foundry workflow

### PR DESCRIPTION
**Pull request by gosuto-inzasheru**
closes #95

### CODE REVIEW

**Comment by gosuto-inzasheru** [comment]
i used the outdated `actions/setup-node@v3` on purpose, to verify dependabot will successfully attempt to bump it to `@v4`

yarn cache is successfully saved at the end:
```
Post job cleanup.
/usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P -C /home/runner/work/robosaver/robosaver --files-from manifest.txt --use-compress-program zstdmt
Cache Size: ~110 MB (114847701 B)
Cache saved successfully
Cache saved with the key: node-cache-Linux-yarn-70ef04d488dc4cdde1[2](https://github.com/onchainification/robosaver/actions/runs/9919181788/job/27404734374?pr=97#step:10:2)d235ce84557517dcfd51bdd93ce03ce5b07ae84048ded
```

**Comment by gosuto-inzasheru** [comment]
i cant figure out why the first commit is responsible for changes in the codecov report: https://app.codecov.io/gh/onchainification/robosaver/commit/43fe21f1f8894d6a0dd276b1f4b6ac647e7c4a01/indirect-changes

**Comment by gosuto-inzasheru** [comment]
it is however not related to this pr; i get the same coverage summary on the main branch

we should investigate more but indifferent of this pr

**Comment by gosuto-inzasheru** [comment]
ok i think i figured it out, @petrovska-petro you once pushed to main and i think those changed were thus never covered by codecov. _somehow_ now they are, hence the delta in coverage in this pr

this pr will therefor also close #79 and #81

im not yet convinced of #80 (ref: https://app.codecov.io/gh/onchainification/robosaver/pull/97/indirect-changes#6e61a7efb13d1515664c616960f618f8-L109)

**Review by petrovska-petro — APPROVED** [review]
nice having on ci as well the whole dry flow of the scripts and make sure runs w/o hiccups ✅ 

great to see the addition of our old friend dependabot 🤖

**Comment by petrovska-petro** [comment]
> im not yet convinced of https://github.com/onchainification/robosaver/issues/80 (ref: https://app.codecov.io/gh/onchainification/robosaver/pull/97/indirect-changes#6e61a7efb13d1515664c616960f618f8-L109)

this is weird actually, nothing changed on this pr that hits more on that specific line 🤔

**Pull request merged**
